### PR TITLE
payment-gateway done

### PR DESCRIPTION
**Pull request by DarkThemeKnight**

### CODE REVIEW

**Comment by DarkThemeKnight** [comment]
So i added a payment part of the code. 
I needed to edit the way you send logs to the database to ensure that i can deduct the balance if dustbin is open to the respective owner. that's  what i did sha.

**Comment by raydev10101** [comment]
Thank you so much for this
I'll test it out and let you know

**Comment by DarkThemeKnight** [comment]
Okay Fixed a bug now

**Comment by DarkThemeKnight** [comment]
added docs

**Pull request merged**
